set(RESUMEGAME_ROOT_DIR Graphics/ResumeGame)

set(RESUMEGAME_INC_DIR
  ${RESUMEGAME_ROOT_DIR})
set( RESUMEGAME_SRC_DIR
  ${RESUMEGAME_ROOT_DIR})

set( RESUMEGAME_INC
  ${RESUMEGAME_INC_DIR}/ResumeGame.hpp )

set( RESUMEGAME_SRC
  ${RESUMEGAME_SRC_DIR}/ResumeGame.cpp )
