set(MENUPAUSE_ROOT_DIR Graphics/MenuPause)

set(MENUPAUSE_INC_DIR
  ${MENUPAUSE_ROOT_DIR})
set( MENUPAUSE_SRC_DIR
  ${MENUPAUSE_ROOT_DIR})

set( MENUPAUSE_INC
  ${MENUPAUSE_INC_DIR}/MenuPause.hpp )

set( MENUPAUSE_SRC
  ${MENUPAUSE_SRC_DIR}/MenuPause.cpp )
