set(MULTIPLAYER_ROOT_DIR Game/Multiplayer)

set(MULTIPLAYER_INC_DIR
  ${MULTIPLAYER_ROOT_DIR})
set( MULTIPLAYER_SRC_DIR
  ${MULTIPLAYER_ROOT_DIR})

set( MULTIPLAYER_INC
  ${MULTIPLAYER_INC_DIR}/Server.hpp )

set( MULTIPLAYER_SRC
  ${MULTIPLAYER_SRC_DIR}/Server.cpp )
