set(SETTINGSMENU_ROOT_DIR Graphics/SettingsMenu)

set(SETTINGSMENU_INC_DIR
  ${SETTINGSMENU_ROOT_DIR})
set( SETTINGSMENU_SRC_DIR
  ${SETTINGSMENU_ROOT_DIR})

set( SETTINGSMENU_INC
  ${SETTINGSMENU_INC_DIR}/settingsMenu.hpp )

set( SETTINGSMENU_SRC
  ${SETTINGSMENU_SRC_DIR}/settingsMenu.cpp )